---
- name: Install code-server
  hosts: all
  become: true
  vars:
    codeserver_version: "4.106.3"
    codeserver_url: "https://github.com/coder/code-server/releases/download/v4.106.3/code-server-4.106.3-linux-amd64.tar.gz"
    install_path: "/usr/local/share"
  
  tasks:
    - name: Download code-server
      get_url:
        url: "{{ codeserver_url }}"
        dest: "/tmp/code-server-{{ codeserver_version }}-linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract code-server to /usr/local/share
      unarchive:
        src: "/tmp/code-server-{{ codeserver_version }}-linux-amd64.tar.gz"
        dest: "{{ install_path }}"
        remote_src: yes
        creates: "{{ install_path }}/code-server-{{ codeserver_version }}-linux-amd64"

    - name: Create symbolic link /usr/lib/code-server
      file:
        src: "{{ install_path }}/code-server-{{ codeserver_version }}-linux-amd64"
        dest: "/usr/lib/code-server"
        state: link

    - name: Create symbolic link /usr/bin/code-server
      file:
        src: "{{ install_path }}/code-server-{{ codeserver_version }}-linux-amd64/bin/code-server"
        dest: "/usr/bin/code-server"
        state: link

    - name: Create /usr/lib/code-server directory
      file:
        path: "/usr/lib/code-server"
        state: directory
        mode: '0755'

    - name: Create code-server systemd service
      template:
        src: code-server.service.j2
        dest: /etc/systemd/system/code-server.service
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start code-server service
      systemd:
        name: code-server
        state: started
        enabled: yes
